### PR TITLE
Misc changes

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by flyinghead** [comment]
I can't remember exactly why Xcode 15.3 was used but I'm pretty sure it was to fix something.

**Comment by scribam** [comment]
Related PR https://github.com/flyinghead/flycast/pull/1498

Xcode 15.0 changelog with the issue: https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking
> - Binaries using symbols with a weak definition crash at runtime on iOS 14/macOS 12 or older. This impacts primarily C++ projects due to their extensive use of weak symbols. (114813650) (FB13097713)
Workaround: Bump the minimum deployment target to iOS 15, macOS 12, watchOS 8 or tvOS 15, or add -Wl,-ld_classic to the OTHER_LDFLAGS build setting.
> - Weak symbol imports are linked as non-weak imports, when used from LTO object files. (115521975) (FB13171424)
Workaround: Add -Wl,-weak_reference_mismatches,weak or -Wl,-ld_classic options to the OTHER_LDFLAGS build setting.

Xcode 15.1 changelog with the issue **fixed**: https://developer.apple.com/documentation/xcode-release-notes/xcode-15_1-release-notes#Linking
> - Fixed: Binaries using symbols with a weak definition crash at runtime on iOS 14/macOS 12 or older. This impacts primarily C++ projects due to their extensive use of weak symbols. (114813650) (FB13097713)
> - Fixed: Weak symbol imports are linked as non-weak imports, when used from LTO object files. (115521975) (FB13171424)

So any Xcode version >= 15.1 should be fine

**Comment by vkedwardli** [comment]
Yes it was 15.0 at that time which had issue, it's safe to remove the version pinning now

**Comment by scribam** [comment]
libzip 1.10.1 fails to build with MinGW + GCC 14.1. I am going to update the submodule which will fix the issue

**Comment by vkedwardli** [comment]
And actually we should can still support 10.9 by manually adding libarclite, and the version warning before 10.13 is just a warning

**Pull request merged**
