### PR TITLE
Increase L2+ / R2+ trigger sensitivity for digital buttons

### LINKED ISSUE #1188: L2+ /  R2+ trigger sensitivity with fighting games
MacBook Air M1 - Ventura 13.5.2. DualSense 5 Controller via USB

The problem is that when i use the standard gamepad config for fighting games (i.e. Street Fighter series), the trigger buttons R2 and L2 are usually mapped to 3 kicks and heavy kick. For example, on my PS5 console the triggers send signals instantly (when slightly pressed), but with Flycast i have to push the trigger almost all the way down - ergo moves don't come out properly or not at all. 

Is there any possibility to increase the threshold in a future release? 

Kind regards, Georg

### PR DESCRIPTION
**Pull request by vkedwardli**
Only reduce the threshold for Dreamcast digital buttons, when the target axis is L2 (leftTrigger) or R2 (rightTrigger).

Fixes #1188.

### CODE REVIEW

**Comment by flyinghead** [comment]
Not 100% sure about iOS but Android needs some changes too.

**Comment by vkedwardli** [comment]
Oh iOS and Android are not using SDL2 for input
Are these the only 2 platforms?

**Comment by flyinghead** [comment]
I believe so. Windows/UWP, Linux, macOS and Switch use SDL.

**Comment by vkedwardli** [comment]
It looks like iOS is handled by `gamepad_btn_input` directly?

https://github.com/flyinghead/flycast/blob/139f2485724dc590c81d268aca0baae5b5d40a8b/shell/apple/emulator-ios/emulator/ios_gamepad.h#L212-L219

**Comment by flyinghead** [comment]
Let's assume iOS is ok.

However Android isn't quite correct: gamepads on Android sometimes have triggers named AXIS_BRAKE/AXIS_GAS or AXIS_Z/AXIS_RZ. The code for this mess is in the `DefaultInputMapping` constructor. It would be better to call `get_axis_code(DC_AXIS_LT/DC_AXIS_RT)` to get the actual trigger codes after the input mapper is initialized.

**Comment by flyinghead** [comment]
Thank you!

**Comment by gktonic** [comment]
Thank you both very much!

**Pull request merged**
