### PR TITLE
libretro: another apple platforms build fix

### PR DESCRIPTION
**Pull request by warmenhoven**

### CODE REVIEW

**Comment by flyinghead** [comment]
I actually ran into this issue compiling standalone on macOS

**Comment by warmenhoven** [comment]
I think it's dependent on which Xcode version you use. I couldn't reproduce it on my computer with 14.3.1 but both of our build computers with older Xcode versions failed.

**Comment by flyinghead** [comment]
I'm running Xcode 12.4

**Comment by warmenhoven** [comment]
Our Mac builder uses 12.2, and our ios/tvos builder uses 14.0.1.

**Comment by vkedwardli** [comment]
I ran into this problem after the big Dev to Master merge

**Pull request merged**
