### PR TITLE
Use std::thread to upscale with xBRZ

### PR DESCRIPTION
**Pull request by scribam**
Goal is to remove the openmp dependency.

Is deposterization still usable/useful for flycast? It seems to be the only part left which uses openmp and it requires to define `DEPOSTERIZE` manually.

### CODE REVIEW

**Comment by flyinghead** [comment]
deposterization is not used and can be removed.

However, are you sure that using std::thread this way for upscaling is equivalent to using openmp performance-wise? I have no idea.

PS: finally fixed bitrise CI for pull requests ;)

**Comment by scribam** [comment]
Arch Linux, GCC 9.3.0, Core i5-8400H 4 cores / 8 threads
Game launched for testing : Dreamcast Bios
Average of the first 2000 values measured

**default emu.cfg + pvr.MaxThreads = 3 (default) + rend.TextureUpscale = 4**

Average time spent on UpscalexBRZ with OpenMP : 442.421 microseconds
Average time spent on UpscalexBRZ with std::thread : 844.096 microseconds

**default emu.cfg + pvr.MaxThreads = 7 + rend.TextureUpscale = 4**

Average time spent on UpscalexBRZ with OpenMP : 1473.22 microseconds
Average time spent on UpscalexBRZ with std::thread : 1000.61 microseconds

It looks like OpenMP is a better choice when using a lower number of threads allocated to xBRZ. Not sure if 0.4ms matters though.
Strangely, with more threads allocated, the results are worst for OpenMP and std::thread :thinking:

**Comment by flyinghead** [comment]
Since you have only 4 physical cores, it's probably not a good idea to use more than 4 threads. Hyper-threading won't help since all threads are busy and it will just add overhead due to context switches.

The other thing is the cost of creating and joining the std::threads for each texture upscaling. OpenMP uses a thread pool so threads are created once and reused instead of being created/destroyed every time. This probably explains why OpenMP is faster than std::thread in your first test.

You might want to look at std::async, which can be used with a thread pool. (That is, if you really want to get rid of OpenMP. Personally I don't have a problem with it.)

**Comment by scribam** [comment]
Thanks for the feedback. I tried with std::async but I didn't managed to have better performance so let's close this PR.

**Pull request closed without merging**
