### PR TITLE
Use service button for coins

### PR DESCRIPTION
**Pull request by j8r**
~It is more logical, most consoles and emulators like RetroArch uses the Guide (PS/Home/X) button to bring the menu.~
Use service button for coins.

### CODE REVIEW

**Comment by flyinghead** [comment]
This is going to create some issues on some platforms. For instance I don't think the Guide button is available on xbox.
Also this doesn't change the default mapping on Android and iOS, which don't use SDL.

I'm fine with mapping the Service button instead of the Coin button. But I'd rather not change the menu one, unless we have a cross-platform consistent change. (And this is increasingly difficult with all the supported platforms).

**Comment by j8r** [comment]
The Guide button is available on Xbox controllers, it is the X home button.
RetroArch does it, and it is cross platform. Why would the back button be more cross platform than the guide one?

The only case I see is for controllers which don't have a guide/home button.

**Comment by j8r** [comment]
I'll look at how to do with other platforms then. Both mappings are needed to play games.

**Comment by j8r** [comment]
I changed the place where the service button is declared, otherwise it won't be taken in the default mappings, only when clicking on the Reset button.

**Comment by GABO1423** [comment]
> The Guide button is available on Xbox controllers, it is the X home button. RetroArch does it, and it is cross platform. Why would the back button be more cross platform than the guide one?
> 
> The only case I see is for controllers which don't have a guide/home button.

I think @flyinghead meant the actual Xbox port (for Xbox One/Series consoles), which can't use the Xbox button because that opens the Xbox guide.

**Comment by j8r** [comment]
Anyone knows what mapping has RetroArch on this consoles?

**Comment by flyinghead** [comment]
Yes, I meant the XBox One/Series platform, not just Xbox controllers.

By the way I did a quick test on Android and the Guide button is unavailable there as well (it returns to the home Android screen).

**Comment by j8r** [comment]
Ok, then I'll revert the change.

**Comment by GABO1423** [comment]
> Anyone knows what mapping has RetroArch on this consoles?

The guide button by default, some consoles like the Wii U can use it, but for others like the Xbox you need to set a button combo instead.

**Comment by j8r** [comment]
So maybe it would be fine to also have different mapping for the different platforms?
It is so much more logical on PC, which I believe is the most used platform, to have the Home button for the menu.

Besides, likely most people on consoles and Android will use Flycast through RetroArch instead of compiling the standalone emulator themselves.

**Comment by flyinghead** [comment]
The golden rule (to me at least) is that the default settings *must* work, even if they are not optimal. And the Home/Guide button may not be available on some gamepads. Users can still remap all the buttons to their liking.

Input is a major source of bugs and regressions so I'd rather avoid introducing more complexity.

**Pull request merged**
