### PR TITLE
Update Vulkan dependencies

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by scribam** [comment]
Can someone test this on macOS? I would like to know if MoltenVK still works

**Comment by flyinghead** [comment]
I get a null pointer segv at startup with vulkan. No issue with Open GL.
```
2022-09-18 13:05:33.634 Flycast[94420:10952789] linux/common.cpp:70 E[COMMON]: SIGSEGV @ 0x7fff72c6be52 -> 0x0 was not in vram, dynacode:0
```

**Comment by vkedwardli** [comment]
[`vulkan_context.cpp` Line 234](https://github.com/scribam/flycast/blob/fb0f22f3ce31790f3aae5fbf1ea0e8bd602a1c26/core/rend/vulkan/vulkan_context.cpp#L234)
```diff
- NOTICE_LOG(RENDERER, "Vulkan API %s. Device %s", vulkan11 ? "1.1" : "1.0", properties->deviceName);
+ NOTICE_LOG(RENDERER, "Vulkan API %s. Device %s", vulkan11 ? "1.1" : "1.0", properties->deviceName.data());
```

**Comment by scribam** [comment]
Thank you for your feedback! I pushed the suggested fix.

**Comment by vkedwardli** [comment]
I can switch to Vulkan on the Mac build now 🎉

**Pull request merged**
