### PR TITLE
cmake: use more system libs

### PR DESCRIPTION
**Pull request by abouvier**

### CODE REVIEW

**Comment by vkedwardli** [comment]
Windows build: `libxxhash.dll` is missing

**Comment by abouvier** [comment]
You can disable one system lib and force use of the vendor one with: `cmake (...) -DCMAKE_DISABLE_FIND_PACKAGE_xxHash=ON`

https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html

**Comment by vkedwardli** [comment]
Can we use the system lib and link it statically so that the user can launch Flycast without extra dependency?

**Comment by abouvier** [comment]
Yes, install a static system lib :p

**Comment by flyinghead** [comment]
It's usual and recommended to use system libs on linux but not so much on other platforms.

Flycast.exe doesn't have any dependency besides system dlls and I'd rather keep it this way.
Other platforms need dependent shared libraries to be packaged with the app (android, iOS, macOS, ...)

It's not practical to have to disable find package for many packages on several platforms. And even on linux I'm not sure it's worth the trouble for these relatively uncommon libraries. Build environments change without notice so it's best not to rely too much on them.

**Pull request merged**
