### PR TITLE
Support for multi-processor compilation with MSVC (/MP option)

### PR DESCRIPTION
**Pull request by BigEvilCorporation**
Adds the /MP compile flag on MSVC to allow for quicker compile times

### CODE REVIEW

**Comment by flyinghead** [comment]
Do we need to make this configurable? Is there any reason not to want the /MP flag?

**Comment by BigEvilCorporation** [comment]
Probably not, playing it safe since I don't have a UWP or MingW32 environment to make sure it doesn't break other Windows configs

**Comment by flyinghead** [comment]
mingw32 doesn't use MSVC so it won't be affected. And UWP is built on regular windows so /MP should work just fine.
So I'd say just enable it for MSVC and we'll see how it goes.

**Comment by BigEvilCorporation** [comment]
Cool, shall I commit that change or will you fix it up during the merge?

**Comment by flyinghead** [comment]
If you can commit that will save me the fix up. I'll just squash all commits together.

**Comment by flyinghead** [comment]
That's not right: you still need `if (MSVC)` to enable this option not just `if (WIN32)`

**Pull request merged**
