### PR TITLE
Texture Upscaling for iOS

### PR DESCRIPTION
**Pull request by vkedwardli**
Didn't know there is actual demand for this feature (requested by MaGi_TekK), so here we go!

- Use `build_ios_openmp.sh` to build `OpenMP.xcframework` (since fat binary by `lipo` cannot support arm64 iOS + arm64 iPhone Simulator)
- GitHub runner would only build arm64 (`--disableSimulator`)
- Manually linking the static library inside xcframework [until CMake can support linking xcframework](https://gitlab.kitware.com/cmake/cmake/-/issues/21752))

### CODE REVIEW

**Comment by knsjoon** [comment]
Thank you for the openMP for ios! 
I have one question: do I need to change some settings on xcode in order to use openMP? It seems that my code keeps using only one thread..

**Comment by vkedwardli** [comment]
@knsjoon during the cmake conf phrase, you should be able to see it is trying locate OpenMP, I have added the below message for iOS:
```
-- Finding OpenMP.xcframework for iOS
-- Could NOT find OpenMP.xcframework, compile it using shell/apple/emulator-ios/OpenMP/build_ios_openmp.sh
```
then you need to `build_ios_openmp.sh` first, and run cmake again (when in doubt, clear the build folder)
The generated Xcode project should have linked OpenMP iOS arm version for you now 
(I would recommend you to use [generate_xcode_project.command](https://github.com/flyinghead/flycast/blob/master/shell/apple/generate_xcode_project.command))

If you want to play with iPhone Simulator, the library is compiled for x86_64 and arm also, but you have to link it manually

**Comment by DarvishKamaliaDL** [comment]
@knsjoon were you ever able to get your app to use more than one thread?

**Comment by vkedwardli** [comment]
[@DarvishKamaliaDL ](https://github.com/flyinghead/flycast/actions/runs/4918429105/jobs/8784744043#step:11:30)
The latest build is still able to found the OpenMP framework, do you have difficulties linking it?

**Comment by DarvishKamaliaDL** [comment]
I was able to link but couldn't get it to use more than one thread until I added `-Xclang -fopenmp` to the projects `Other C Flags`. Thanks for building this!

**Comment by vkedwardli** [comment]
@DarvishKamaliaDL glad that it is working for you, FYR the flag should be set automatically by CMake when OpenMP is detected.  https://github.com/flyinghead/flycast/blob/06270e66c8ba7d166dcd8552315c1b8c5a90703b/CMakeLists.txt#L341

**Pull request merged**
