### PR TITLE
libchdr: add build option for using system library

### PR DESCRIPTION
**Pull request by bsdcode**
The added build option USE_HOST_LIBCHDR allows to build with libchdr provided by the system. The option is disabled by default.

I have no experience with building for Android, Apple or the Switch, so I don't know if it's also necessary to exclude them from using the system library.

### CODE REVIEW

**Comment by flyinghead** [comment]
Thanks!

**Comment by abouvier** [comment]
Why did you exclude libretro build? If `USE_HOST_LIBCHDR` is set, it should be enabled for every target.

**Comment by bsdcode** [comment]
I have little experience with libretro cores and how RetroArch handles this. There was no other reason other than inexperience on the libretro topic. Now on a second look I was probably wrong here, because chdr-static was always build previously.

**Comment by flyinghead** [comment]
Fixed by https://github.com/flyinghead/flycast/commit/df78a781ec4ad671109070cbfb9123967364a4d8

**Comment by abouvier** [comment]
By the way, `libretro-common` also contains a copy of libchdr headers in `core/deps/libretro-common/include/libchdr`.
They are searched for, and can hijack the system headers because of this line:
https://github.com/flyinghead/flycast/blob/df78a781ec4ad671109070cbfb9123967364a4d8/CMakeLists.txt#L779

**Pull request merged**
