### PR TITLE
CMake refactoring

### PR DESCRIPTION
**Pull request by scribam**
Update the CMake build and add CI Integration for:
- Apple (Xcode 11.4.1)
- FreeBSD (clang 8.0.1, without artifacts)
- Microsoft Visual C++ (Visual Studio 2019, 32 and 64 bits)
- MinGW (gcc 8.1.0)
- Ubuntu (gcc 7.5.0, with unit tests)

I think you have to setup an account on Cirrus CI to use the FreeBSD CI. It should work out-of-the-box for GitHub actions.

Some options are available to tweak the build:
- ENABLE_CTEST to create the build for unit testing (default: OFF)
- ENABLE_OPROFILE to enable the OProfile library in the dynarec  (default: OFF)
- TEST_AUTOMATION to create the build for automatic testing (default: OFF)

I also have a working commit which allows to build for Android with CMake but I would like to have these changes merged first before to submit it.

### CODE REVIEW

**Comment by vkedwardli** [comment]
Hi @scribam, I noticed that the compiled artifacts for macOS is not a valid application.

Would like to know do the artifacts built by cmake are supposed to be run by end users? Or the main purpose of the Github Actions is for compilation checking only?

Thanks

**Comment by scribam** [comment]
@vkedwardli It would be obviously better if the artifacts could be run by end users but I have no way to test it. From your comment, it looks like it does not work so any improvements are welcome 🙂

**Comment by vkedwardli** [comment]
@scribam thanks, I will see if cmake is capable for building a proper macOS app, if not, should I change it to use `xcodebuild`? And should the CI build a release binary or debug binary?

**Comment by scribam** [comment]
@vkedwardli I am not sure but I think the xcodebuild is done here: https://github.com/flyinghead/flycast/blob/master/bitrise.yml
I added CMake and Github Actions at the same time but the previous build systems are still here and supported until CMake can replace them I guess.
If the target is end users, a release binary is better.

**Pull request merged**
